In [5]:
import pathlib
import pandas as pd
import numpy as np

import json

In [6]:
input_path = pathlib.Path('./SBJ_2102_001')

In [8]:
전유부 = pd.read_csv(input_path.joinpath('1.세종시_전유부.csv'),encoding="utf-8")
표제부 = pd.read_csv(input_path.joinpath('2.세종시_표제부.csv'),encoding="utf-8")
아파트매매 = pd.read_csv(input_path.joinpath('3.세종시_아파트(매매)_실거래가.csv'),encoding="utf-8")
연립매매 = pd.read_csv(input_path.joinpath('4.세종시_연립다세대(매매)_실거래가.csv'),encoding="utf-8")
다가구매매 = pd.read_csv(input_path.joinpath('5.세종시_단독다가구(매매)_실거래가.csv'),encoding="utf-8")
오피스텔매매 = pd.read_csv(input_path.joinpath('6.세종시_오피스텔(매매)_실거래가.csv'),encoding="utf-8")
아파트전월세 = pd.read_csv(input_path.joinpath('7.세종시_아파트(전월세)_실거래가.csv'),encoding="utf-8")
연립전월세 = pd.read_csv(input_path.joinpath('8.세종시_연립다세대(전월세)_실거래가.csv'),encoding="utf-8")
다가구전월세 = pd.read_csv(input_path.joinpath('9.세종시_단독다가구(전월세)_실거래가.csv'),encoding="utf-8")
오피스텔전월세 = pd.read_csv(input_path.joinpath('10.세종시_오피스텔(전월세)_실거래가.csv'),encoding="utf-8")
상업매매 = pd.read_csv(input_path.joinpath('11.세종시_상업업무용(매매)_실거래가.csv'),encoding="utf-8")
토지매매 = pd.read_csv(input_path.joinpath('12.세종시_토지(매매)_실거래가.csv'),encoding="utf-8")
분양권 = pd.read_csv(input_path.joinpath('13.세종시_분양권_실거래가.csv'),encoding="utf-8")
상권정보 = pd.read_csv(input_path.joinpath('14.세종시_상권정보.csv'),encoding="utf-8")
상권정보업종 = pd.read_csv(input_path.joinpath('15.세종시_상권정보_업종코드.csv'),encoding="utf-8")

전입자수 = pd.read_csv(input_path.joinpath('20.세종시_전입자수.csv'),encoding="utf-8")
전출자수 = pd.read_csv(input_path.joinpath('21.세종시_전출자수.csv'),encoding="utf-8")
연령별인구 = pd.read_csv(input_path.joinpath('22.세종시_연령별_인구현황.csv'),encoding="utf-8")
월평균소비지출액 = pd.read_csv(input_path.joinpath('25.세종시_가구_월평균_소비지출액.csv'),encoding="utf-8")
거주기간 = pd.read_csv(input_path.joinpath('26.세종시_거주기간.csv'),encoding="utf-8")
월평균소득 = pd.read_csv(input_path.joinpath('27.세종시_월평균_가구소득.csv'),encoding="utf-8")
지역별세대수 = pd.read_csv(input_path.joinpath('28.세종시_지역별_세대원수별_세대수.csv'),encoding="utf-8")
거주의사 = pd.read_csv(input_path.joinpath('29.세종시_거주의사(향후).csv'),encoding="utf-8")

In [90]:
아파트매매['단지명'].value_counts()

범지기마을11단지(영무예다음)    830
조치원죽림자이             710
가재마을 5단지            695
가재마을4단지(센트레빌)       561
대우푸르지오(10단지)        539
                   ...
가재마을8단지               2
씨즈파크뷰                 1
팔팔                    1
새샘마을8단지               1
새샘마을7단지               1
Name: 단지명, Length: 187, dtype: int64

In [34]:
#분류
거주기간_읍면동=거주기간.loc[1:3]
거주기간_성별=거주기간.loc[4:5]
거주기간_연령별=거주기간.loc[6:12]
거주기간_교육정도별=거주기간.loc[13:16]
거주기간_직업별=거주기간.loc[17:22]
거주기간_혼인상태별=거주기간.loc[23:25]
거주기간_가구소득별=거주기간.loc[26:33]
거주기간_맞벌이유무=거주기간.loc[34:35]
거주기간_주거형태별=거주기간.loc[36:]

In [66]:
거주의사_읍면동=거주의사.loc[1:3]
거주의사_성별=거주의사.loc[4:5]
거주의사_연령별=거주의사.loc[6:14]
거주의사_교육정도별=거주의사.loc[15:18]
거주의사_직업별=거주의사.loc[19:24]
거주의사_혼인상태별=거주의사.loc[25:27]
거주의사_가구소득별=거주의사.loc[28:35]
거주의사_맞벌이유무=거주의사.loc[36:37]
거주의사_주거형태별=거주의사.loc[38:]

In [78]:
지역별세대수.sort_values('계',ascending=False)

      읍면동      계    1인    2인    3인    4인    5인   6인  7인  8인  9인  10인이상
11  새 롬 동  20495  6019  3980  4283  4754  1201  201  39  12   4      2
0    조치원읍  19472  8295  4165  3042  2729   944  220  63   9   4      1
12  도 담 동  13136  5002  2117  2383  2825   667  106  29   3   4      0
15  고 운 동  11436  2025  2341  2839  3240   814  145  19   7   4      2
16  소 담 동  10973  2754  2268  2597  2545   671  106  27   1   1      3
14  종 촌 동  10691  2525  2049  2420  2847   675  120  34  17   2      2
13  아 름 동   7560  1058  1262  1858  2656   597   98  20   7   1      3
17  보 람 동   6810  1536  1363  1544  1802   471   69  20   2   2      1
10  한 솔 동   6333  1069  1134  1468  1944   584  101  25   5   1      2
4   금 남 면   4509  2128  1283   589   328   122   41  12   6   0      0
18  대 평 동   3926   857   977   932   886   228   33   9   4   0      0
6   연 서 면   3834  1863  1022   484   276   129   38  16   3   2      1
5   장 군 면   3453  1956   806   332   200   106   35  11   6   1      0
3   부 강 면   3249  1603   821   420   273    93   34   3   0   0      2
7   전 의 면   3045  1551   753   352   244   107   29   8   0   1      0
8   전 동 면   2130  1224   491   213   124    57   15   6   0   0      0
2   연 동 면   1680   834   461   206   114    44   14   5   1   0      1
1   연 기 면   1445   855   299   133   101    36   11   7   1   2      0
9   소 정 면   1231   565   308   160   127    58    9   1   2   1      0