In [2]:
import pathlib
import pandas as pd
import numpy as np

import json

In [3]:
input_path = pathlib.Path('./data')

In [4]:
전입자수 = pd.read_csv(input_path.joinpath('20.세종시_전입자수.csv'),encoding="utf-8")
전출자수 = pd.read_csv(input_path.joinpath('21.세종시_전출자수.csv'),encoding="utf-8")

In [5]:
전입자수['년도']=0
전입자수=전입자수.astype({'년월':str})
전입자수=전입자수.astype({'년도':str})
전입자수['년도']=전입자수["년월"].str[0:4]

전출자수['년도']=0
전출자수=전출자수.astype({'년월':str})
전출자수=전출자수.astype({'년도':str})
전출자수['년도']=전출자수["년월"].str[0:4]

In [6]:
#전입수는 비슷비슷
전입자수합계_년도별전입=전입자수.groupby(by=['년도']).sum().groupby(level=[0]).cumsum()
전입자수합계_년도별전입.sort_values('년도',ascending=True).head(20)

        전입자수
년도
2017  507673
2018  517171
2019  491174
2020  500284
2021   40286

In [7]:
#전출은 갈수록 증가하는중
전출자수합계_년도별전입=전출자수.groupby(by=['년도']).sum().groupby(level=[0]).cumsum()
전출자수합계_년도별전입.sort_values('년도',ascending=True).head(20)

        전출자수
년도
2017  331362
2018  338430
2019  368346
2020  457294
2021   33780

<h1>세종시 내 이사분석</h1>

In [8]:
전입_세종에서전출=전입자수[전입자수['전출시']=='세종특별자치시']
전출_세종으로전입=전출자수[전출자수['전입시']=='세종특별자치시']

In [9]:
#세종에서 세종으로 전입/전출은 계속증가
전입_세종에서전출=전입_세종에서전출.groupby(by=['년도']).sum().groupby(level=[0]).cumsum()
전입_세종에서전출.sort_values('년도',ascending=True).head(20)

        전입자수
년도
2017  251609
2018  255864
2019  248629
2020  264518
2021   19386

In [10]:

전출_세종으로전입=전출_세종으로전입.groupby(by=['년도']).sum().groupby(level=[0]).cumsum()
전출_세종으로전입.sort_values('년도',ascending=True).head(20)

        전출자수
년도
2017  210228
2018  207558
2019  221636
2020  272405
2021   21329

<h1>타지역 이사분석</h1>

In [11]:
전입_타지역전출=전입자수[전입자수['전출시']!='세종특별자치시']#타지역->세종
전출_타지역전입=전출자수[전출자수['전입시']!='세종특별자치시']#세종->타지역

In [12]:
전입_타지역전출

            년월  전입자수 세종전입행정동   전출시   전출시군구   전출읍면동    년도
0       201701     1    조치원읍   강원도     강릉시     교1동  2017
1       201701     6    조치원읍   강원도     동해시     천곡동  2017
2       201701    14    조치원읍   강원도     속초시      교동  2017
3       201701    21    조치원읍   강원도     양양군      서면  2017
4       201701     2    조치원읍   강원도     원주시     원인동  2017
...        ...   ...     ...   ...     ...     ...   ...
108077  202101     3     다정동  충청북도  청주시흥덕구    복대1동  2021
108078  202101    56     다정동  충청북도  청주시흥덕구     오송읍  2021
108079  202101    32     다정동  충청북도  청주시흥덕구     옥산면  2021
108080  202101     8     다정동  충청북도     충주시  교현·안림동  2021
108081  202101     9     다정동  충청북도     충주시    중앙탑면  2021

[98249 rows x 7 columns]

In [13]:
#타지역에서 세종으로 전입하는 수는 증가하는듯 했으나 다시 감소
전입_타지역전출_년도별=전입_타지역전출.groupby(by=['년도']).sum().groupby(level=[0]).cumsum()
전입_타지역전출_년도별.sort_values('년도',ascending=True).head(20)

        전입자수
년도
2017  256064
2018  261307
2019  242545
2020  235766
2021   20900

In [14]:
#세종에서 타지역으로 전출하는 수는 갈수록 크게 증가중
전출_타지역전입_년도별=전출_타지역전입.groupby(by=['년도']).sum().groupby(level=[0]).cumsum()
전출_타지역전입_년도별.sort_values('년도',ascending=True)

        전출자수
년도
2017  121134
2018  130872
2019  146710
2020  184889
2021   12451

In [15]:
#타지역에서 세종으로 이사오는 곳은 대전, 충북, 충남이 압도적
전입_타지역전출_전출시=전입_타지역전출.groupby(by=['전출시']).sum().groupby(level=[0]).cumsum()
전입_타지역전출_전출시.sort_values('전입자수',ascending=False)

           전입자수
전출시
대전광역시    254368
충청북도     231053
충청남도     220788
경기도       90530
서울특별시     38982
경상북도      33467
전라북도      29952
경상남도      25790
전라남도      23388
강원도       21352
대구광역시      9334
광주광역시      9260
제주특별자치도    8319
인천광역시      7628
부산광역시      6779
울산광역시      5592

In [16]:
전입_타지역전출

            년월  전입자수 세종전입행정동   전출시   전출시군구   전출읍면동    년도
0       201701     1    조치원읍   강원도     강릉시     교1동  2017
1       201701     6    조치원읍   강원도     동해시     천곡동  2017
2       201701    14    조치원읍   강원도     속초시      교동  2017
3       201701    21    조치원읍   강원도     양양군      서면  2017
4       201701     2    조치원읍   강원도     원주시     원인동  2017
...        ...   ...     ...   ...     ...     ...   ...
108077  202101     3     다정동  충청북도  청주시흥덕구    복대1동  2021
108078  202101    56     다정동  충청북도  청주시흥덕구     오송읍  2021
108079  202101    32     다정동  충청북도  청주시흥덕구     옥산면  2021
108080  202101     8     다정동  충청북도     충주시  교현·안림동  2021
108081  202101     9     다정동  충청북도     충주시    중앙탑면  2021

[98249 rows x 7 columns]

In [17]:
전입_타지역전출_전출시

           전입자수
전출시
강원도       21352
경기도       90530
경상남도      25790
경상북도      33467
광주광역시      9260
대구광역시      9334
대전광역시    254368
부산광역시      6779
서울특별시     38982
울산광역시      5592
인천광역시      7628
전라남도      23388
전라북도      29952
제주특별자치도    8319
충청남도     220788
충청북도     231053

In [18]:
import pandas as pd
print("pandas version: ", pd.__version__)
pd.set_option('display.max_row', 2000)
pd.set_option('display.max_columns', 100)
년도별_전입_타지역전출전입자수_피벗=전입_타지역전출.pivot_table(index=['년도','세종전입행정동','전출시'],values=['전입자수'],aggfunc=[sum])

pandas version:  1.1.5

In [19]:
년도별_전입_타지역전출전입자수_피벗

                        sum
                       전입자수
년도   세종전입행정동 전출시
2017 고운동     강원도        337
             경기도       1379
             경상남도       384
             경상북도       465
             광주광역시      216
             대구광역시      153
             대전광역시     3306
             부산광역시       70
             서울특별시      397
             울산광역시       45
             인천광역시      135
             전라남도       437
             전라북도       518
             제주특별자치도     63
             충청남도      4232
             충청북도      3805
     금남면     강원도        100
             경기도        551
             경상남도       163
             경상북도       135
             광주광역시       56
             대구광역시       44
             대전광역시     1525
             부산광역시       11
             서울특별시      165
             울산광역시        3
             인천광역시       46
             전라남도       177
             전라북도       178
             제주특별자치도     23
             충청남도      1445
             충청북도       507
     도담동     강원도        441
             경기도       2691
             경상남도       755
             경상북도       974
             광주광역시      306
             대구광역시      274
             대전광역시     4192
             부산광역시      220
             서울특별시     2003
             울산광역시      171
             인천광역시      270
             전라남도       947
             전라북도      1166
             제주특별자치도    276
             충청남도      4635
             충청북도      5509
     보람동     강원도        367
             경기도       2081
             경상남도       667
             경상북도       875
             광주광역시      324
             대구광역시      167
             대전광역시    21678
             부산광역시      138
             서울특별시      792
             울산광역시      147
             인천광역시      180
             전라남도       427
             전라북도      1012
             제주특별자치도    205
             충청남도      5535
             충청북도     10227
     부강면     강원도        329
             경기도        574
             경상남도        99
             경상북도       222
             광주광역시       33
             대구광역시       70
             대전광역시      466
             부산광역시       39
             서울특별시       94
             울산광역시       15
             인천광역시       24
             전라남도        90
             전라북도        85
             제주특별자치도      6
             충청남도       657
             충청북도      1615
     새롬동     강원도        144
             경기도        554
             경상남도       203
             경상북도       206
             광주광역시      103
             대구광역시       43
             대전광역시     3564
             부산광역시       44
             서울특별시      296
             울산광역시       41
             인천광역시       25
             전라남도        23
             전라북도       313
             제주특별자치도     60
             충청남도      2448
             충청북도      2075
     소정면     강원도         11
             경기도        194
             경상남도         8
             경상북도        53
             광주광역시        8
             대구광역시        1
             대전광역시       19
             부산광역시       47
             서울특별시       37
             인천광역시        4
             전라남도         2
             충청남도       743
             충청북도       104
     아름동     강원도        644
             경기도       1652
             경상남도       523
             경상북도       699
             광주광역시      158
             대구광역시       97
             대전광역시     3338
             부산광역시      127
             서울특별시      740
             울산광역시       99
             인천광역시      118
             전라남도       269
             전라북도       631
             제주특별자치도     91
             충청남도      3786
             충청북도      4699
     연기면     강원도         71
             경기도        200
             경상남도        46
             경상북도        76
             광주광역시        5
             대구광역시        9
             대전광역시      354
             부산광역시        3
             서울특별시       73
             울산광역시        7
             인천광역시        6
             전라남도       145
             전라북도       139
             제주특별자치도     14
             충청남도       509
             충청북도       601
     연동면     강원도         19
             경기도        174
             경상남도        27
             경상북도       119
             대구광역시        3
             대전광역시      166
             부산광역시        4
             서울특별시       49
             울산광역시       15
             인천광역시       42
             전라남도        26
             전라북도        48
             제주특별자치도      5
             충청남도       193
             충청북도       684
     연서면     강원도        222
             경기도        626
             경상남도       127
             경상북도       135
             광주광역시       20
             대구광역시       13
             대전광역시      703
             부산광역시        7
             서울특별시      107
             울산광역시       21
             인천광역시      105
             전라남도       218
             전라북도       235
             제주특별자치도     15
             충청남도      1645
             충청북도      1171
     장군면     강원도        146
             경기도        583
             경상남도       142
             경상북도       223
             광주광역시       65
             대구광역시       39
             대전광역시      743
             부산광역시       31
             서울특별시      134
             울산광역시       12
             인천광역시       60
             전라남도       172
             전라북도       275
             제주특별자치도      6
             충청남도      2873
             충청북도       981
     전동면     강원도         44
             경기도        105
             경상남도        22
             경상북도        70
             광주광역시        2
             대구광역시        5
             대전광역시       76
             부산광역시        3
             서울특별시       73
             전라남도        16
             전라북도        50
             제주특별자치도     40
             충청남도       228
             충청북도       521
     전의면     강원도        107
             경기도        476
             경상남도       212
             경상북도        56
             광주광역시        8
             대구광역시        2
             대전광역시      193
             부산광역시       10
             서울특별시       48
             인천광역시       19
             전라남도        65
             전라북도       114
             제주특별자치도     20
             충청남도      1096
             충청북도       397
     조치원읍    강원도        700
             경기도       2323
             경상남도       582
             경상북도      1228
             광주광역시      132
             대구광역시      375
             대전광역시     1338
             부산광역시      123
             서울특별시      769
             울산광역시      243
             인천광역시      192
             전라남도       675
             전라북도       491
             제주특별자치도     86
             충청남도      3769
             충청북도      8859
     종촌동     강원도        531
             경기도       2914
             경상남도       680
             경상북도       475
             광주광역시      204
             대구광역시      277
             대전광역시     4510
             부산광역시      199
             서울특별시     1084
             울산광역시       97
             인천광역시      210
             전라남도       561
             전라북도       663
             제주특별자치도    179
             충청남도      5367
             충청북도      4149
     한솔동     강원도        973
             경기도       4703
             경상남도      1404
             경상북도      1270
             광주광역시      466
             대구광역시      538
             대전광역시    26466
             부산광역시      449
             서울특별시     2141
             울산광역시      330
             인천광역시      406
             전라남도       792
             전라북도      1595
             제주특별자치도    377
             충청남도     12546
             충청북도     13673
2018 고운동     강원도        420
             경기도       1819
             경상남도       657
             경상북도       528
             광주광역시      238
             대구광역시      129
             대전광역시     4712
             부산광역시      168
             서울특별시      494
             울산광역시      133
             인천광역시      105
             전라남도       506
             전라북도       578
             제주특별자치도    204
             충청남도      6181
             충청북도      6369
     금남면     강원도         91
             경기도        598
             경상남도       116
             경상북도       142
             광주광역시       54
             대구광역시       10
             대전광역시     1532
             부산광역시       36
             서울특별시      147
             울산광역시       33
             인천광역시       45
             전라남도       141
             전라북도       137
             제주특별자치도     72
             충청남도      1169
             충청북도       510
     대평동     강원도        118
             경기도        737
             경상남도       106
             경상북도       268
             광주광역시       45
             대구광역시       75
             대전광역시     5884
             부산광역시       58
             서울특별시      252
             울산광역시        7
             인천광역시       34
             전라남도       110
             전라북도       102
             제주특별자치도      9
             충청남도      1212
             충청북도      1571
     도담동     강원도        602
             경기도       2553
             경상남도       862
             경상북도       821
             광주광역시      287
             대구광역시      260
             대전광역시     2839
             부산광역시      219
             서울특별시     1891
             울산광역시      156
             인천광역시      142
             전라남도       980
             전라북도      1001
             제주특별자치도    340
             충청남도      3413
             충청북도      5658
     보람동     강원도        427
             경기도       1952
             경상남도       497
             경상북도       666
             광주광역시      303
             대구광역시      181
             대전광역시    11895
             부산광역시      174
             서울특별시      808
             울산광역시       70
             인천광역시      269
             전라남도       511
             전라북도       807
             제주특별자치도     17
             충청남도      5393
             충청북도      5776
     부강면     강원도        255
             경기도        453
             경상남도       295
             경상북도       384
             광주광역시       10
             대구광역시       39
             대전광역시      490
             부산광역시       31
             서울특별시      146
             울산광역시        8
             인천광역시       41
             전라남도       131
             전라북도        60
             제주특별자치도     26
             충청남도       824
             충청북도      1631
     새롬동     강원도        911
             경기도       5324
             경상남도      1479
             경상북도      1932
             광주광역시      730
             대구광역시      580
             대전광역시    23610
             부산광역시      362
             서울특별시     2218
             울산광역시      441
             인천광역시      422
             전라남도      1237
             전라북도      2145
             제주특별자치도    548
             충청남도     15813
             충청북도     13740
     소담동     강원도        135
             경기도        554
             경상남도       106
             경상북도       316
             광주광역시      135
             대구광역시       74
             대전광역시     4189
             부산광역시       27
             서울특별시      200
             울산광역시       29
             인천광역시       68
             전라남도       168
             전라북도       142
             제주특별자치도      1
             충청남도      1141
             충청북도      1729
     소정면     강원도         57
             경기도        127
             경상남도        30
             경상북도        20
             광주광역시       12
             대전광역시       24
             서울특별시       37
             인천광역시       10
             전라남도         3
             전라북도         6
             제주특별자치도     10
             충청남도       838
             충청북도       134
     아름동     강원도        446
             경기도       1182
             경상남도       494
             경상북도       462
             광주광역시      164
             대구광역시      119
             대전광역시     2580
             부산광역시      113
             서울특별시      594
             울산광역시      128
             인천광역시       89
             전라남도       245
             전라북도       451
             제주특별자치도    286
             충청남도      2620
             충청북도      4190
     연기면     강원도         64
             경기도        279
             경상남도       124
             경상북도        18
             광주광역시       13
             대구광역시        2
             대전광역시      287
             부산광역시        7
             서울특별시       62
             울산광역시        4
             인천광역시       20
             전라남도        87
             전라북도        22
             제주특별자치도      2
             충청남도       356
             충청북도       249
     연동면     강원도         87
             경기도        151
             경상남도        75
             경상북도        28
             광주광역시        8
             대구광역시        5
             대전광역시      197
             부산광역시       11
             서울특별시       53
             울산광역시        1
             인천광역시        7
             전라남도        14
             전라북도        41
             제주특별자치도      2
             충청남도       193
             충청북도       624
     연서면     강원도        257
             경기도        492
             경상남도       106
             경상북도       472
             광주광역시       10
             대구광역시       17
             대전광역시      419
             부산광역시       10
             서울특별시      120
             울산광역시        9
             인천광역시       36
             전라남도       146
             전라북도       251
             제주특별자치도      2
             충청남도       848
             충청북도      1339
     장군면     강원도        173
             경기도        621
             경상남도       293
             경상북도        65
             광주광역시       42
             대구광역시       89
             대전광역시      727
             부산광역시       41
             서울특별시      193
             울산광역시       29
             인천광역시       26
             전라남도       266
             전라북도       166
             제주특별자치도     34
             충청남도      2318
             충청북도       605
     전동면     강원도         30
             경기도        121
             경상남도         4
             경상북도        12
             광주광역시        2
             대전광역시       58
             부산광역시       25
             서울특별시       56
             울산광역시       11
             인천광역시       10
             전라남도        44
             제주특별자치도     27
             충청남도       351
             충청북도       389
     전의면     강원도         58
             경기도        382
             경상남도        58
             경상북도        43
             광주광역시       13
             대구광역시        6
             대전광역시      120
             부산광역시        3
             서울특별시      104
             울산광역시       13
             인천광역시       22
             전라남도        41
             전라북도        39
             제주특별자치도     19
             충청남도       978
             충청북도       280
     조치원읍    강원도        838
             경기도       2802
             경상남도       914
             경상북도       774
             광주광역시      230
             대구광역시      161
             대전광역시     1621
             부산광역시      220
             서울특별시      942
             울산광역시      180
             인천광역시      232
             전라남도       697
             전라북도       666
             제주특별자치도    447
             충청남도      4038
             충청북도      7570
     종촌동     강원도        707
             경기도       1814
             경상남도       540
             경상북도       448
             광주광역시      255
             대구광역시      200
             대전광역시     3525
             부산광역시      281
             서울특별시      935
             울산광역시      154
             인천광역시      176
             전라남도       512
             전라북도       561
             제주특별자치도    208
             충청남도      4961
             충청북도      4125
     한솔동     강원도        157
             경기도       1236
             경상남도       238
             경상북도       489
             광주광역시      121
             대구광역시       80
             대전광역시     2932
             부산광역시      109
             서울특별시      495
             울산광역시       50
             인천광역시       88
             전라남도       348
             전라북도       420
             제주특별자치도    155
             충청남도      2922
             충청북도      1866
2019 고운동     강원도        318
             경기도       1992
             경상남도       656
             경상북도       739
             광주광역시      290
             대구광역시      376
             대전광역시     7357
             부산광역시      123
             서울특별시      503
             울산광역시      118
             인천광역시      159
             전라남도       801
             전라북도       846
             제주특별자치도    142
             충청남도      7462
             충청북도      6101
     금남면     강원도        139
             경기도        408
             경상남도       124
             경상북도       158
             광주광역시        8
             대구광역시       85
             대전광역시     1278
             부산광역시       38
             서울특별시      144
             울산광역시       56
             인천광역시       50
             전라남도        34
             전라북도       151
             제주특별자치도     15
             충청남도      1063
             충청북도       709
     대평동     강원도        148
             경기도        698
             경상남도       199
             경상북도       272
             광주광역시       53
             대구광역시       40
             대전광역시     4518
             부산광역시       27
             서울특별시      266
             울산광역시       38
             인천광역시       77
             전라남도       173
             전라북도       217
             제주특별자치도     20
             충청남도      2615
             충청북도      2184
     도담동     강원도        469
             경기도       2479
             경상남도       874
             경상북도       954
             광주광역시      317
             대구광역시      327
             대전광역시     3017
             부산광역시      206
             서울특별시     2114
             울산광역시       55
             인천광역시      277
             전라남도       984
             전라북도       799
             제주특별자치도    426
             충청남도      4033
             충청북도      3909
     보람동     강원도        183
             경기도       1071
             경상남도       205
             경상북도       525
             광주광역시      182
             대구광역시      171
             대전광역시     6540
             부산광역시       66
             서울특별시      403
             울산광역시       77
             인천광역시       74
             전라남도       248
             전라북도       404
             제주특별자치도     57
             충청남도      2891
             충청북도      3595
     부강면     강원도        242
             경기도        762
             경상남도       116
             경상북도       244
             광주광역시       21
             대구광역시       47
             대전광역시      398
             부산광역시       12
             서울특별시      155
             울산광역시       22
             인천광역시       30
             전라남도       103
             전라북도        78
             제주특별자치도     47
             충청남도       561
             충청북도      1370
     새롬동     강원도        881
             경기도       3592
             경상남도       823
             경상북도      1502
             광주광역시      535
             대구광역시      388
             대전광역시    12059
             부산광역시      296
             서울특별시     1996
             울산광역시      349
             인천광역시      331
             전라남도      1215
             전라북도      1293
             제주특별자치도    306
             충청남도     10196
             충청북도      7726
     소담동     강원도        295
             경기도       2312
             경상남도       506
             경상북도       729
             광주광역시      145
             대구광역시      237
             대전광역시    16148
             부산광역시      161
             서울특별시      895
             울산광역시      240
             인천광역시      178
             전라남도       477
             전라북도       721
             제주특별자치도    238
             충청남도      5368
             충청북도      8219
     소정면     강원도        109
             경기도        110
             경상남도        21
             경상북도        18
             광주광역시        2
             대구광역시        1
             대전광역시       43
             부산광역시        2
             서울특별시       31
             울산광역시        7
             인천광역시       14
             전라남도        16
             전라북도        17
             충청남도       683
             충청북도        97
     아름동     강원도        213
             경기도       1323
             경상남도       504
             경상북도       241

In [39]:
import matplotlib.pyplot as plt

# matplotlib 폰트설정
# plt.rc('font', family='NanumGothicOTF') # For MacOS
plt.rc('font', family='NanumGothic') # For Windows
print(plt.rcParams['font.family'])

%matplotlib inline

년도별_전입_타지역전출전입자수_피벗.query("전출시==['경상북도']&년도==['2020']")#.plot.bar(figsize=(10,10))
#년도별_전입_타지역전출전입자수_피벗.query("전출시==['경기도']&년도==['2018']")#.plot.bar(figsize=(10,10))
#년도별_전입_타지역전출전입자수_피벗.query("전출시==['경기도']&년도==['2019']")#.plot.bar(figsize=(10,10))
#년도별_전입_타지역전출전입자수_피벗.query("전출시==['강원도']&년도==['2020']").plot.bar(figsize=(60,30))

#plt.show()

['NanumGothic']

                    sum
                   전입자수
년도   세종전입행정동 전출시
2020 고운동     경상북도   617
     금남면     경상북도   255
     다정동     경상북도   287
     대평동     경상북도   193
     도담동     경상북도  1167
     보람동     경상북도   443
     부강면     경상북도   178
     새롬동     경상북도  1304
     소담동     경상북도   695
     소정면     경상북도    33
     아름동     경상북도   506
     연기면     경상북도   214
     연동면     경상북도   121
     연서면     경상북도   413
     장군면     경상북도   345
     전동면     경상북도    38
     전의면     경상북도   112
     조치원읍    경상북도  1204
     종촌동     경상북도   691
     한솔동     경상북도   380

In [21]:
년도별_전입_타지역전출전입자수_피벗.query("전출시==['경기도']&년도==['2017']")
#도별_전입_타지역전출전입자수_피벗.query("전출시==['강원도']&년도==['2018']")
#년도별_전입_타지역전출전입자수_피벗.query("전출시==['강원도']&년도==['2019']")

                   sum
                  전입자수
년도   세종전입행정동 전출시
2017 고운동     경기도  1379
     금남면     경기도   551
     도담동     경기도  2691
     보람동     경기도  2081
     부강면     경기도   574
     새롬동     경기도   554
     소정면     경기도   194
     아름동     경기도  1652
     연기면     경기도   200
     연동면     경기도   174
     연서면     경기도   626
     장군면     경기도   583
     전동면     경기도   105
     전의면     경기도   476
     조치원읍    경기도  2323
     종촌동     경기도  2914
     한솔동     경기도  4703